apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbs
  template:
    metadata:
      labels:
        app: dbs
    spec:
      containers:
        - name: dbs
          image: swr.af-south-1.myhuaweicloud.com/ralf/db-app:8dc031913cc0c7712f244e98604a33acf22ebd43
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: db-secret
          resources:
            limits:
              cpu: 100m 
              memory: 100Mi 
            requests:
              cpu: 100m 
              memory: 100Mi 
