apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-db  #The name of your secret provider class. It is user defined
spec:
  provider: cce #The value is a fixed value
  parameters: 
    objects: |
    #ObjectName is the name of the secret created on Huawei Cloud
    #ObjectType is a fixed value as well
    #ObjectVersion; you can use "latest" so that the spc picks the latest version
    #jmesPath is used to extract key-value pairs from objects in JSON format. CCE Secrets Manager for DEW uses this tool to support Secret mounting.
    #path is the key name defined in your CSMS secret
    #objectAlias 
      - objectName: "DB-connection"        
        objectType: "csms"
        objectVersion: "v1"
        jmesPath:
          - path: MYSQL_HOST
            objectAlias: dbhost
          - path: MYSQL_PASSWORD
            objectAlias: dbpassword
          - path: MYSQL_USER
            objectAlias: dbusername      
          - path: MYSQL_DB     
            objectAlias: dbname     
            
  # Create a CCE secret based on the CSMS secret and mount the secret to a pod.
  #Here I isync the secret in my CSMS as kubernetes secret
  # "key" will get value from "objectName"; objectName is an Alias for the actual secret in CSMS 
  secretObjects:                
    - secretName: dev-secrets #name of the secret, spc will auto create this in your CCE
      type: Opaque
      data:
        - objectName: dbhost 
          key: MYSQL_HOST  
        - objectName: dbpassword
          key: MYSQL_PASSWORD
        - objectName: dbusername
          key: MYSQL_USER
        - objectName: dbname
          key: MYSQL_DB           
