apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-db
spec:
  provider: cce     # The value is fixed at cce.
  secretObjects:
  - data:
    - key: db-host
      objectName: MYSQL_HOST
    - key: db-user
      objectName: MYSQL_USER
    - key: db-password
      objectName: MYSQL_PASSWORD
    - key: db-db
      objectName: MYSQL_DB                              
  parameters:
    objects: |
      array:
        - |
          objectName:MYSQL_HOST
          objectType: csms
          objectVersion: ""
        - |
          objectName:MYSQL_USER
          objectType: csms
          objectVersion: ""
        - |
          objectName:MYSQL_PASSWORD
          objectType: csms
          objectVersion: ""
        - |
          objectName:MYSQL_DB
          objectType: csms
          objectVersion: ""                              

