apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-db
spec:
  provider: cce     # The value is fixed at cce.
  parameters:
    objects: |
      - objectName: "ralf"
        objectVersion: "v1"
        objectType: "csms"
