apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-test  #The name of your secret provider class. It is user defined
spec:
  provider: cce #The value is a fixed value
  parameters: 
    objects: |
      - objectName: "DB-connection"        
        objectType: "csms"
        objectVersion: "v1"
        jmesPath:
          - path: MYSQL_HOST
            objectAlias: dbhost
          - path: MYSQL_PASSWORD
            objectAlias: dbpassword
          - path: MYSQL_USER
            objectAlias: dbusername      
          - path: MYSQL_DB     
            objectAlias: dbname     
            
  # Create a CCE secret based on the CSMS secret and mount the secret to a pod.
  #Here I isync the secret in my CSMS as kubernetes secret
  # "key" will get value from "objectName"; objectName is an Alias for the actual secret in CSMS 
  secretObjects:                
    - secretName: test-today #name of the secret, spc will auto create this in your CCE
      type: Opaque
      data:
        - objectName: dbhost 
          key: MYSQL_HOST  
        - objectName: dbpassword
          key: MYSQL_PASSWORD
        - objectName: dbusername
          key: MYSQL_USER
        - objectName: dbname
          key: MYSQL_DB           
