apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-db
spec:
  provider: cce     # The value is fixed at cce.
  secretObjects:
  - data:
    - key: MYSQL_HOST
      objectName: DB-connection
    - key: MYSQL_USER
      objectName: DB-connection
    - key: MYSQL_PASSWORD
      objectName: DB-connection
    - key: MYSQL_DB     
      objectName: DB-connection    
    secretName: dev-secrets
    type: Opaque  
  parameters:
    objects: |
          - objectName: "DB-connection"
            objectVersion: "v1"
            objectType: "csms"                            

