apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-db
spec:
  provider: cce
  parameters: 
    objects: |
      - objectName: "DB-connection"
        objectType: "csms"
        objectVersion: "v1"
        jmesPath:
          - path: MYSQL_HOST
            objectAlias: dbhost
          - path: MYSQL_PASSWORD
            objectAlias: dbpassword
          - path: MYSQL_USER
            objectAlias: dbusername      
          - path: MYSQL_DB     
            objectAlias: dbname     
  # Create a CCE secret based on the CSMS secret and mount the secret to a pod.
  secretObjects:                
    - secretName: dev-secrets
      type: Opaque
      data:
        - objectName: dbhost
          key: MYSQL_HOST
        - objectName: dbpassword
          key: MYSQL_PASSWORD
        - objectName: dbusername
          key: MYSQL_USER
        - objectName: dbname
          key: MYSQL_DB           
