apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-db
spec:
  provider: cce     # The value is fixed at cce.
  secretObjects:
  - secretName: foosecret
    type: Opaque
    labels:
      app: "dbs"
    data:
    - objectName: ralf
      key: MYSQL_HOST
  parameters:
    objects: |
          - objectName: "ralf"
            objectVersion: "v1"
            objectType: "csms"
