apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: swr.af-south-1.myhuaweicloud.com/ralf/api:d33b72f57fc7c183deaaae619d93f69318f6360a
        ports:
        - containerPort: 3000
