apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: swr.af-south-1.myhuaweicloud.com/ralf/api:96e07fc4dbb5f89ca5103431e64f88e1a1d5d5bc
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"  # Request 200 millicpu (0.2 CPU)
            memory: "128Mi"  # Request 128 megabytes
          limits:
            cpu: "100m"  # Limit to 500 millicpu (0.5 CPU)
            memory: "128Mi"  # Limit to 256 megabytes
