apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort  # Change service type to NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30517  # Define a specific nodePort value (replace with desired port number)
