name: Example Workflow

on:
  push:
    branches:
      - master

jobs:
  example_job:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "This is running on a push to the main branch"
