name: Debugging action
on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

        
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: get CCE Cluster Credentials
        uses: JimohHWC/cce-cred-action@v1.0.0
        with:
          ak: ${{ secrets.ACCESSKEY }}
          sk: ${{ secrets.SECRETACCESSKEY }}
          region: "af-south-1"
          project_id: "eecc7ec81ad346adbcde0a07fa343cb0"
          cluster_id: "8817579e-f98a-11ee-990c-0255ac1000eb"
          #project_id: "3e7cb44b-4b49-43b5-93df-d78f8a24e2dc"
          
      - name: Debugging
        run: |
          kubectl cluster-info
          kubectl get nodes
